name: Build, Test and Release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Get latest release
        uses: actions/github-script@v3.1
        id: get-latest-release
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            try {
                var latestRelease = await github.repos.getLatestRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo
                });
                return latestRelease.data.tag_name;
            } catch (error) {
                if (error.message === 'Not Found') {
                    return '0.0.0';
                } else {
                    core.setFailed(error.message)
                }
            }

      - name: Print
        run: echo ${{ steps.get-latest-release.outputs.result }}
